-- ============================================================
-- Favor Kids Quest: Read My Bible 2026 - Supabase Schema
-- ============================================================

-- 1. Kids / Explorers Profile Table
CREATE TABLE IF NOT EXISTS public.rmb_kids (
  id TEXT PRIMARY KEY,                       -- UUID generated by client device
  first_name TEXT NOT NULL,
  last_name TEXT,
  age INTEGER,
  grade TEXT,
  gender TEXT,
  country TEXT,
  parent_name TEXT,
  parent_contact TEXT,
  consent BOOLEAN DEFAULT FALSE,
  consent_at TIMESTAMPTZ,
  chapters_completed INTEGER DEFAULT 0,
  current_chapter INTEGER DEFAULT 1,
  streak INTEGER DEFAULT 0,
  home_stage TEXT,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Audit Log of Events (Sign up, chapters read, home upgrades, logins)
CREATE TABLE IF NOT EXISTS public.rmb_events (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  eid TEXT UNIQUE NOT NULL,                  -- Client-generated unique event ID to guarantee idempotency
  kid_id TEXT REFERENCES public.rmb_kids(id) ON DELETE CASCADE,
  event_name TEXT NOT NULL,                  -- e.g. 'Signed up', 'Read a chapter', 'Home upgraded'
  chapter TEXT,
  details TEXT,
  occurred_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Kids' Reflections, Quiz Answers, and Voice Recordings
CREATE TABLE IF NOT EXISTS public.rmb_answers (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  eid TEXT UNIQUE NOT NULL,                  -- Client-generated unique answer/event ID
  kid_id TEXT REFERENCES public.rmb_kids(id) ON DELETE CASCADE,
  chapter TEXT,
  title TEXT,
  question TEXT,
  answer_text TEXT,
  audio_url TEXT,                            -- Supabase Storage URL for voice recordings
  audio_id TEXT,                             -- IndexedDB clip ID from device
  mime_type TEXT,
  occurred_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Indexes for efficient queries
CREATE INDEX IF NOT EXISTS idx_rmb_events_kid ON public.rmb_events(kid_id);
CREATE INDEX IF NOT EXISTS idx_rmb_events_occurred_at ON public.rmb_events(occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_rmb_answers_kid ON public.rmb_answers(kid_id);
CREATE INDEX IF NOT EXISTS idx_rmb_answers_occurred_at ON public.rmb_answers(occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_rmb_kids_streak ON public.rmb_kids(streak DESC);
CREATE INDEX IF NOT EXISTS idx_rmb_kids_country ON public.rmb_kids(country);

-- Row Level Security (RLS)
ALTER TABLE public.rmb_kids ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rmb_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rmb_answers ENABLE ROW LEVEL SECURITY;

-- Service role has full access (used by Vercel backend serverless functions)
CREATE POLICY "Service role full access on rmb_kids"
  ON public.rmb_kids FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Service role full access on rmb_events"
  ON public.rmb_events FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Service role full access on rmb_answers"
  ON public.rmb_answers FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Optional: Allow public read of leaderboard stats (without exposing parent contacts)
CREATE OR REPLACE VIEW public.rmb_leaderboard AS
  SELECT
    id,
    first_name,
    country,
    streak,
    chapters_completed,
    home_stage,
    updated_at
  FROM public.rmb_kids
  WHERE consent = true
  ORDER BY streak DESC, chapters_completed DESC;

-- Storage Bucket for Voice Recordings
INSERT INTO storage.buckets (id, name, public)
VALUES ('rmbkids-voice', 'rmbkids-voice', true)
ON CONFLICT (id) DO NOTHING;

-- Public read access for voice recordings
CREATE POLICY "Public read access for rmbkids-voice"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'rmbkids-voice');

-- Service role upload access for rmbkids-voice
CREATE POLICY "Service role upload access for rmbkids-voice"
  ON storage.objects FOR INSERT
  TO service_role
  WITH CHECK (bucket_id = 'rmbkids-voice');
